{-
The sequence of triangle numbers is generated by adding the natural numbers. So the 7^(th) triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
-}

import List (find, group)

triangles :: [Integer]
triangles = tail $ scanl (+) 0 [1..]

-- via http://en.wikipedia.org/wiki/Divisor_function
-- d(n)=\prod_{i=1}^r (a_i+1). 

numDivisors :: [Integer] -> Int
numDivisors primes = foldr (\(x, pow) acc -> (pow + 1) * acc) 1 primes'
        where primes' = map powerTuples $ group primes
              powerTuples (n:ns) = (n, length (n:ns))

primeFactors x = pf x [] (2:[3,5..])
    where pf x' fs (p:ps)
            | p > x' = fs
            | x' `mod` p == 0 = pf (x' `div` p) (p:fs) (p:ps)
            | otherwise = pf x' fs ps

main = putStr $ show $ find ((> 500) . numDivisors . primeFactors) triangles

-- $ time ./12                       (12-29 13:36)
-- 1.12s user 0.02s system 96% cpu 1.182 total

