-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

-- Find the sum of all the even-valued terms in the sequence which do not exceed four million.

fib :: Integer -> Integer

fib 0 = 1
fib 1 = 1
fib x = fib(x - 1) + fib(x - 2)

main = putStr $ show $ sum $ filter even $ fibsUnderFourMil
    where fibsUnderFourMil = takeWhile (< 4000000) $ map fib [1..]
